#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "pre-commit hook started (husky)"
echo "-------------------------------"
echo "checking code matches xo/prettier checks "
npm run lint
echo "running npm packages audit"
npm audit
