#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "pre-push hook started (husky)"
echo "-------------------------------"
echo "running integration tests"
npm run test:it
echo "validating builds succesfully"
npm run build