#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "pre-commit hook started (husky)"
echo "-------------------------------"
echo "checking and altering code to match prettier formatting rules "
npm run lint
echo "running npm packages audit"
npm audit
