#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "pre-push hook started (husky)"
echo "-------------------------------"
echo "running unit tests"
npm run test:unit
echo "validating builds succesfully"
npm run build